### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeType' of undefined

### ISSUE THREAD

**Issue by XMegamanX** [tuananh/atom-xpath#1]
[Enter steps to reproduce:]

1. Enter a request
2. Press Return

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [xpath](https://github.com/tuananh/atom-xpath) package 0.2.1-0

### Stack Trace

Uncaught TypeError: Cannot read property 'nodeType' of undefined

```
At /Users/megamanx/.atom/packages/xpath/node_modules/xpath/xpath.js:1787

TypeError: Cannot read property 'nodeType' of undefined
    at Function.PathExpr.getRoot (/packages/xpath/node_modules/xpath/xpath.js:1787:18)
    at Function.PathExpr.applyLocationPath (/packages/xpath/node_modules/xpath/xpath.js:2076:54)
    at PathExpr.evaluate (/packages/xpath/node_modules/xpath/xpath.js:2091:23)
    at Object.Functions.string (/packages/xpath/node_modules/xpath/xpath.js:3559:23)
    at FunctionCall.evaluate (/packages/xpath/node_modules/xpath/xpath.js:2440:11)
    at PathExpr.applyFilter (/packages/xpath/node_modules/xpath/xpath.js:2056:23)
    at PathExpr.evaluate (/packages/xpath/node_modules/xpath/xpath.js:2084:29)
    at XPath.evaluate (/packages/xpath/node_modules/xpath/xpath.js:1317:25)
    at XPathExpression.evaluate (/packages/xpath/node_modules/xpath/xpath.js:4315:26)
    at Object.exports.selectWithResolver (/packages/xpath/node_modules/xpath/xpath.js:4738:26)
    at Object.exports.select (/packages/xpath/node_modules/xpath/xpath.js:4718:17)
    at InputDialog.callback (/packages/xpath/lib/xpath.js:36:30)
    at InputDialog.confirm (/packages/xpath/node_modules/@aki77/atom-input-dialog/src/input-dialog.js:48:12)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:22 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:10.5.0 xpath:query (input.hidden-input)
     -0:07.3.0 core:backspace (input.hidden-input)
     -0:05.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-formatter-jsbeautify 1.1.2 
atom-runner 2.7.1 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
color-picker 2.2.5 
compare-files 0.8.1 
file-icons 2.1.16 
intentions 1.1.5 
language-sql-mysql 0.3.1 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.0.0 
linter-rubocop 2.2.3 
linter-ui-default 1.6.10 
nuclide 0.259.0 
nuclide-format-js 0.0.41 
react-es6-snippets 0.3.0 
rubocop-auto-correct 1.5.1 
vue2-autocomplete 0.1.0-alpha.4 
webbox-color 0.5.9 
xml-tools 0.2.1 
xpath 0.2.1-0 
```

**Comment by Malfix25** [comment]
I also have this issue, is there some step I can take to get past it?

**Comment by tuananh** [comment]
sorry guys, it was just a fun project, kind of publish and forget. i do not plan to maintain this

![image](https://user-images.githubusercontent.com/627278/50484503-5e13cd80-0a23-11e9-96f0-7472285a776a.png)
