### ISSUE TITLE
Uncaught Error: Unterminated string literal: 'Hallo")])�

### ISSUE THREAD

**Issue by petrdunaj** [tuananh/atom-xpath#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [xpath](https://github.com/tuananh/atom-xpath) package 0.2.1-0

### Stack Trace

Uncaught Error: Unterminated string literal: 'Hallo")])

```
At C:\Users\user\.atom\packages\xpath\node_modules\xpath\xpath.js:981

Error: Unterminated string literal: 'Hallo")])
    at /packages/xpath/node_modules/xpath/xpath.js:4254:25)
    at Function.XPathException.fromMessage (/packages/xpath/node_modules/xpath/xpath.js:4271:16)
    at XPathParser.tokenize (/packages/xpath/node_modules/xpath/xpath.js:981:38)
    at XPathParser.parse (/packages/xpath/node_modules/xpath/xpath.js:1228:17)
    at /packages/xpath/node_modules/xpath/xpath.js:4287:17)
    at Object.exports.selectWithResolver (/packages/xpath/node_modules/xpath/xpath.js:4735:19)
    at Object.exports.select (/packages/xpath/node_modules/xpath/xpath.js:4718:17)
    at InputDialog.callback (/packages/xpath/lib/xpath.js:36:30)
    at InputDialog.confirm (/packages/xpath/node_modules/@aki77/atom-input-dialog/src/input-dialog.js:48:12)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:349538)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1256534)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1252668)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:284744)
```

### Commands

```
     -9:24.5.0 core:backspace (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:39.8.0 xpath:query (input.hidden-input)
     -7:05.4.0 find-and-replace:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:04.3.0 core:paste (input.hidden-input)
     -1:27.9.0 xpath:query (input.hidden-input)
     -1:16.5.0 core:move-left (input.hidden-input)
  2x -0:44.1.0 core:backspace (input.hidden-input)
     -0:36.7.0 core:move-right (input.hidden-input)
     -0:36 core:move-left (input.hidden-input)
  2x -0:33.3.0 core:move-right (input.hidden-input)
     -0:32.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
language-docker 1.1.8 
teletype 0.13.4 
xpath 0.2.1-0 
```

**Comment by tuananh** [comment]
Sorry, it's just a pet project to see how atom extension works.
